//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: riak.proto
namespace CorrugatedIron.Messages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbErrorResp")]
  public partial class RpbErrorResp : global::ProtoBuf.IExtensible
  {
    public RpbErrorResp() {}
    
    private byte[] _errmsg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errmsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] errmsg
    {
      get { return _errmsg; }
      set { _errmsg = value; }
    }
    private uint _errcode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"errcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint errcode
    {
      get { return _errcode; }
      set { _errcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbGetServerInfoResp")]
  public partial class RpbGetServerInfoResp : global::ProtoBuf.IExtensible
  {
    public RpbGetServerInfoResp() {}
    

    private byte[] _node = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] node
    {
      get { return _node; }
      set { _node = value; }
    }

    private byte[] _server_version = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"server_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] server_version
    {
      get { return _server_version; }
      set { _server_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbPair")]
  public partial class RpbPair : global::ProtoBuf.IExtensible
  {
    public RpbPair() {}
    
    private byte[] _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] key
    {
      get { return _key; }
      set { _key = value; }
    }

    private byte[] _value = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
