//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: riak_yokozuna.proto
namespace RiakClient.Messages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbYokozunaIndex")]
  public partial class RpbYokozunaIndex : global::ProtoBuf.IExtensible
  {
    public RpbYokozunaIndex() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private byte[] _schema;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"schema", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] schema
    {
      get { return _schema?? null; }
      set { _schema = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool schemaSpecified
    {
      get { return this._schema != null; }
      set { if (value == (this._schema== null)) this._schema = value ? this.schema : (byte[])null; }
    }
    private bool ShouldSerializeschema() { return schemaSpecified; }
    private void Resetschema() { schemaSpecified = false; }
    
    private uint? _n_val;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"n_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint n_val
    {
      get { return _n_val?? default(uint); }
      set { _n_val = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool n_valSpecified
    {
      get { return this._n_val != null; }
      set { if (value == (this._n_val== null)) this._n_val = value ? this.n_val : (uint?)null; }
    }
    private bool ShouldSerializen_val() { return n_valSpecified; }
    private void Resetn_val() { n_valSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbYokozunaIndexGetReq")]
  public partial class RpbYokozunaIndexGetReq : global::ProtoBuf.IExtensible
  {
    public RpbYokozunaIndexGetReq() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name?? null; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (byte[])null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbYokozunaIndexGetResp")]
  public partial class RpbYokozunaIndexGetResp : global::ProtoBuf.IExtensible
  {
    public RpbYokozunaIndexGetResp() {}
    
    private readonly global::System.Collections.Generic.List<RpbYokozunaIndex> _index = new global::System.Collections.Generic.List<RpbYokozunaIndex>();
    [global::ProtoBuf.ProtoMember(1, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RpbYokozunaIndex> index
    {
      get { return _index; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbYokozunaIndexPutReq")]
  public partial class RpbYokozunaIndexPutReq : global::ProtoBuf.IExtensible
  {
    public RpbYokozunaIndexPutReq() {}
    
    private RpbYokozunaIndex _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public RpbYokozunaIndex index
    {
      get { return _index; }
      set { _index = value; }
    }
    private uint? _timeout;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timeout
    {
      get { return _timeout?? default(uint); }
      set { _timeout = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timeoutSpecified
    {
      get { return this._timeout != null; }
      set { if (value == (this._timeout== null)) this._timeout = value ? this.timeout : (uint?)null; }
    }
    private bool ShouldSerializetimeout() { return timeoutSpecified; }
    private void Resettimeout() { timeoutSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbYokozunaIndexDeleteReq")]
  public partial class RpbYokozunaIndexDeleteReq : global::ProtoBuf.IExtensible
  {
    public RpbYokozunaIndexDeleteReq() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbYokozunaSchema")]
  public partial class RpbYokozunaSchema : global::ProtoBuf.IExtensible
  {
    public RpbYokozunaSchema() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content?? null; }
      set { _content = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool contentSpecified
    {
      get { return this._content != null; }
      set { if (value == (this._content== null)) this._content = value ? this.content : (byte[])null; }
    }
    private bool ShouldSerializecontent() { return contentSpecified; }
    private void Resetcontent() { contentSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbYokozunaSchemaPutReq")]
  public partial class RpbYokozunaSchemaPutReq : global::ProtoBuf.IExtensible
  {
    public RpbYokozunaSchemaPutReq() {}
    
    private RpbYokozunaSchema _schema;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"schema", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public RpbYokozunaSchema schema
    {
      get { return _schema; }
      set { _schema = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbYokozunaSchemaGetReq")]
  public partial class RpbYokozunaSchemaGetReq : global::ProtoBuf.IExtensible
  {
    public RpbYokozunaSchemaGetReq() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbYokozunaSchemaGetResp")]
  public partial class RpbYokozunaSchemaGetResp : global::ProtoBuf.IExtensible
  {
    public RpbYokozunaSchemaGetResp() {}
    
    private RpbYokozunaSchema _schema;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"schema", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public RpbYokozunaSchema schema
    {
      get { return _schema; }
      set { _schema = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}