//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: riak_search.proto
// Note: requires additional types generated from: riak.proto
namespace RiakClient.Messages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbSearchDoc")]
  public partial class RpbSearchDoc : global::ProtoBuf.IExtensible
  {
    public RpbSearchDoc() {}
    
    private readonly global::System.Collections.Generic.List<RpbPair> _fields = new global::System.Collections.Generic.List<RpbPair>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fields", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RpbPair> fields
    {
      get { return _fields; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbSearchQueryReq")]
  public partial class RpbSearchQueryReq : global::ProtoBuf.IExtensible
  {
    public RpbSearchQueryReq() {}
    
    private byte[] _q;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"q", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] q
    {
      get { return _q; }
      set { _q = value; }
    }
    private byte[] _index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] index
    {
      get { return _index; }
      set { _index = value; }
    }
    private uint? _rows;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rows", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rows
    {
      get { return _rows?? default(uint); }
      set { _rows = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rowsSpecified
    {
      get { return this._rows != null; }
      set { if (value == (this._rows== null)) this._rows = value ? this.rows : (uint?)null; }
    }
    private bool ShouldSerializerows() { return rowsSpecified; }
    private void Resetrows() { rowsSpecified = false; }
    
    private uint? _start;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint start
    {
      get { return _start?? default(uint); }
      set { _start = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startSpecified
    {
      get { return this._start != null; }
      set { if (value == (this._start== null)) this._start = value ? this.start : (uint?)null; }
    }
    private bool ShouldSerializestart() { return startSpecified; }
    private void Resetstart() { startSpecified = false; }
    
    private byte[] _sort;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sort", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] sort
    {
      get { return _sort?? null; }
      set { _sort = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sortSpecified
    {
      get { return this._sort != null; }
      set { if (value == (this._sort== null)) this._sort = value ? this.sort : (byte[])null; }
    }
    private bool ShouldSerializesort() { return sortSpecified; }
    private void Resetsort() { sortSpecified = false; }
    
    private byte[] _filter;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] filter
    {
      get { return _filter?? null; }
      set { _filter = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool filterSpecified
    {
      get { return this._filter != null; }
      set { if (value == (this._filter== null)) this._filter = value ? this.filter : (byte[])null; }
    }
    private bool ShouldSerializefilter() { return filterSpecified; }
    private void Resetfilter() { filterSpecified = false; }
    
    private byte[] _df;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"df", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] df
    {
      get { return _df?? null; }
      set { _df = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dfSpecified
    {
      get { return this._df != null; }
      set { if (value == (this._df== null)) this._df = value ? this.df : (byte[])null; }
    }
    private bool ShouldSerializedf() { return dfSpecified; }
    private void Resetdf() { dfSpecified = false; }
    
    private byte[] _op;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] op
    {
      get { return _op?? null; }
      set { _op = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool opSpecified
    {
      get { return this._op != null; }
      set { if (value == (this._op== null)) this._op = value ? this.op : (byte[])null; }
    }
    private bool ShouldSerializeop() { return opSpecified; }
    private void Resetop() { opSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<byte[]> _fl = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(9, Name=@"fl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> fl
    {
      get { return _fl; }
    }
  
    private byte[] _presort;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"presort", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] presort
    {
      get { return _presort?? null; }
      set { _presort = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool presortSpecified
    {
      get { return this._presort != null; }
      set { if (value == (this._presort== null)) this._presort = value ? this.presort : (byte[])null; }
    }
    private bool ShouldSerializepresort() { return presortSpecified; }
    private void Resetpresort() { presortSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbSearchQueryResp")]
  public partial class RpbSearchQueryResp : global::ProtoBuf.IExtensible
  {
    public RpbSearchQueryResp() {}
    
    private readonly global::System.Collections.Generic.List<RpbSearchDoc> _docs = new global::System.Collections.Generic.List<RpbSearchDoc>();
    [global::ProtoBuf.ProtoMember(1, Name=@"docs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RpbSearchDoc> docs
    {
      get { return _docs; }
    }
  
    private float? _max_score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_score", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float max_score
    {
      get { return _max_score?? default(float); }
      set { _max_score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool max_scoreSpecified
    {
      get { return this._max_score != null; }
      set { if (value == (this._max_score== null)) this._max_score = value ? this.max_score : (float?)null; }
    }
    private bool ShouldSerializemax_score() { return max_scoreSpecified; }
    private void Resetmax_score() { max_scoreSpecified = false; }
    
    private uint? _num_found;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num_found", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num_found
    {
      get { return _num_found?? default(uint); }
      set { _num_found = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool num_foundSpecified
    {
      get { return this._num_found != null; }
      set { if (value == (this._num_found== null)) this._num_found = value ? this.num_found : (uint?)null; }
    }
    private bool ShouldSerializenum_found() { return num_foundSpecified; }
    private void Resetnum_found() { num_foundSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}