//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: riak_dt.proto
namespace RiakClient.Messages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapField")]
  public partial class MapField : global::ProtoBuf.IExtensible
  {
    public MapField() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private MapField.MapFieldType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MapField.MapFieldType type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MapFieldType")]
    public enum MapFieldType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"COUNTER", Value=1)]
      COUNTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SET", Value=2)]
      SET = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER", Value=3)]
      REGISTER = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLAG", Value=4)]
      FLAG = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAP", Value=5)]
      MAP = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEntry")]
  public partial class MapEntry : global::ProtoBuf.IExtensible
  {
    public MapEntry() {}
    
    private MapField _field;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MapField field
    {
      get { return _field; }
      set { _field = value; }
    }
    private long? _counter_value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"counter_value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long counter_value
    {
      get { return _counter_value?? default(long); }
      set { _counter_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool counter_valueSpecified
    {
      get { return this._counter_value != null; }
      set { if (value == (this._counter_value== null)) this._counter_value = value ? this.counter_value : (long?)null; }
    }
    private bool ShouldSerializecounter_value() { return counter_valueSpecified; }
    private void Resetcounter_value() { counter_valueSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<byte[]> _set_value = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(3, Name=@"set_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> set_value
    {
      get { return _set_value; }
    }
  
    private byte[] _register_value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"register_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] register_value
    {
      get { return _register_value?? null; }
      set { _register_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool register_valueSpecified
    {
      get { return this._register_value != null; }
      set { if (value == (this._register_value== null)) this._register_value = value ? this.register_value : (byte[])null; }
    }
    private bool ShouldSerializeregister_value() { return register_valueSpecified; }
    private void Resetregister_value() { register_valueSpecified = false; }
    
    private bool? _flag_value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"flag_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool flag_value
    {
      get { return _flag_value?? default(bool); }
      set { _flag_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool flag_valueSpecified
    {
      get { return this._flag_value != null; }
      set { if (value == (this._flag_value== null)) this._flag_value = value ? this.flag_value : (bool?)null; }
    }
    private bool ShouldSerializeflag_value() { return flag_valueSpecified; }
    private void Resetflag_value() { flag_valueSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<MapEntry> _map_value = new global::System.Collections.Generic.List<MapEntry>();
    [global::ProtoBuf.ProtoMember(6, Name=@"map_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEntry> map_value
    {
      get { return _map_value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DtFetchReq")]
  public partial class DtFetchReq : global::ProtoBuf.IExtensible
  {
    public DtFetchReq() {}
    
    private byte[] _bucket;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bucket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] bucket
    {
      get { return _bucket; }
      set { _bucket = value; }
    }
    private byte[] _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] key
    {
      get { return _key; }
      set { _key = value; }
    }
    private byte[] _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint? _r;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"r", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint r
    {
      get { return _r?? default(uint); }
      set { _r = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rSpecified
    {
      get { return this._r != null; }
      set { if (value == (this._r== null)) this._r = value ? this.r : (uint?)null; }
    }
    private bool ShouldSerializer() { return rSpecified; }
    private void Resetr() { rSpecified = false; }
    
    private uint? _pr;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pr
    {
      get { return _pr?? default(uint); }
      set { _pr = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool prSpecified
    {
      get { return this._pr != null; }
      set { if (value == (this._pr== null)) this._pr = value ? this.pr : (uint?)null; }
    }
    private bool ShouldSerializepr() { return prSpecified; }
    private void Resetpr() { prSpecified = false; }
    
    private bool? _basic_quorum;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"basic_quorum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool basic_quorum
    {
      get { return _basic_quorum?? default(bool); }
      set { _basic_quorum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool basic_quorumSpecified
    {
      get { return this._basic_quorum != null; }
      set { if (value == (this._basic_quorum== null)) this._basic_quorum = value ? this.basic_quorum : (bool?)null; }
    }
    private bool ShouldSerializebasic_quorum() { return basic_quorumSpecified; }
    private void Resetbasic_quorum() { basic_quorumSpecified = false; }
    
    private bool? _notfound_ok;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"notfound_ok", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool notfound_ok
    {
      get { return _notfound_ok?? default(bool); }
      set { _notfound_ok = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool notfound_okSpecified
    {
      get { return this._notfound_ok != null; }
      set { if (value == (this._notfound_ok== null)) this._notfound_ok = value ? this.notfound_ok : (bool?)null; }
    }
    private bool ShouldSerializenotfound_ok() { return notfound_okSpecified; }
    private void Resetnotfound_ok() { notfound_okSpecified = false; }
    
    private uint? _timeout;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"timeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timeout
    {
      get { return _timeout?? default(uint); }
      set { _timeout = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timeoutSpecified
    {
      get { return this._timeout != null; }
      set { if (value == (this._timeout== null)) this._timeout = value ? this.timeout : (uint?)null; }
    }
    private bool ShouldSerializetimeout() { return timeoutSpecified; }
    private void Resettimeout() { timeoutSpecified = false; }
    
    private bool? _sloppy_quorum;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sloppy_quorum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sloppy_quorum
    {
      get { return _sloppy_quorum?? default(bool); }
      set { _sloppy_quorum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sloppy_quorumSpecified
    {
      get { return this._sloppy_quorum != null; }
      set { if (value == (this._sloppy_quorum== null)) this._sloppy_quorum = value ? this.sloppy_quorum : (bool?)null; }
    }
    private bool ShouldSerializesloppy_quorum() { return sloppy_quorumSpecified; }
    private void Resetsloppy_quorum() { sloppy_quorumSpecified = false; }
    
    private uint? _n_val;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"n_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint n_val
    {
      get { return _n_val?? default(uint); }
      set { _n_val = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool n_valSpecified
    {
      get { return this._n_val != null; }
      set { if (value == (this._n_val== null)) this._n_val = value ? this.n_val : (uint?)null; }
    }
    private bool ShouldSerializen_val() { return n_valSpecified; }
    private void Resetn_val() { n_valSpecified = false; }
    
    private bool? _include_context;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"include_context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool include_context
    {
      get { return _include_context?? (bool)true; }
      set { _include_context = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool include_contextSpecified
    {
      get { return this._include_context != null; }
      set { if (value == (this._include_context== null)) this._include_context = value ? this.include_context : (bool?)null; }
    }
    private bool ShouldSerializeinclude_context() { return include_contextSpecified; }
    private void Resetinclude_context() { include_contextSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DtValue")]
  public partial class DtValue : global::ProtoBuf.IExtensible
  {
    public DtValue() {}
    
    private long? _counter_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"counter_value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long counter_value
    {
      get { return _counter_value?? default(long); }
      set { _counter_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool counter_valueSpecified
    {
      get { return this._counter_value != null; }
      set { if (value == (this._counter_value== null)) this._counter_value = value ? this.counter_value : (long?)null; }
    }
    private bool ShouldSerializecounter_value() { return counter_valueSpecified; }
    private void Resetcounter_value() { counter_valueSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<byte[]> _set_value = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(2, Name=@"set_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> set_value
    {
      get { return _set_value; }
    }
  
    private readonly global::System.Collections.Generic.List<MapEntry> _map_value = new global::System.Collections.Generic.List<MapEntry>();
    [global::ProtoBuf.ProtoMember(3, Name=@"map_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEntry> map_value
    {
      get { return _map_value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DtFetchResp")]
  public partial class DtFetchResp : global::ProtoBuf.IExtensible
  {
    public DtFetchResp() {}
    
    private byte[] _context;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] context
    {
      get { return _context?? null; }
      set { _context = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool contextSpecified
    {
      get { return this._context != null; }
      set { if (value == (this._context== null)) this._context = value ? this.context : (byte[])null; }
    }
    private bool ShouldSerializecontext() { return contextSpecified; }
    private void Resetcontext() { contextSpecified = false; }
    
    private DtFetchResp.DataType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DtFetchResp.DataType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private DtValue _value = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DtValue value
    {
      get { return _value; }
      set { _value = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"DataType")]
    public enum DataType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"COUNTER", Value=1)]
      COUNTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SET", Value=2)]
      SET = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAP", Value=3)]
      MAP = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CounterOp")]
  public partial class CounterOp : global::ProtoBuf.IExtensible
  {
    public CounterOp() {}
    
    private long? _increment;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"increment", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long increment
    {
      get { return _increment?? default(long); }
      set { _increment = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool incrementSpecified
    {
      get { return this._increment != null; }
      set { if (value == (this._increment== null)) this._increment = value ? this.increment : (long?)null; }
    }
    private bool ShouldSerializeincrement() { return incrementSpecified; }
    private void Resetincrement() { incrementSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetOp")]
  public partial class SetOp : global::ProtoBuf.IExtensible
  {
    public SetOp() {}
    
    private readonly global::System.Collections.Generic.List<byte[]> _adds = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(1, Name=@"adds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> adds
    {
      get { return _adds; }
    }
  
    private readonly global::System.Collections.Generic.List<byte[]> _removes = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(2, Name=@"removes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> removes
    {
      get { return _removes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapUpdate")]
  public partial class MapUpdate : global::ProtoBuf.IExtensible
  {
    public MapUpdate() {}
    
    private MapField _field;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MapField field
    {
      get { return _field; }
      set { _field = value; }
    }
    private CounterOp _counter_op = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"counter_op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CounterOp counter_op
    {
      get { return _counter_op; }
      set { _counter_op = value; }
    }
    private SetOp _set_op = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"set_op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SetOp set_op
    {
      get { return _set_op; }
      set { _set_op = value; }
    }
    private byte[] _register_op;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"register_op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] register_op
    {
      get { return _register_op?? null; }
      set { _register_op = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool register_opSpecified
    {
      get { return this._register_op != null; }
      set { if (value == (this._register_op== null)) this._register_op = value ? this.register_op : (byte[])null; }
    }
    private bool ShouldSerializeregister_op() { return register_opSpecified; }
    private void Resetregister_op() { register_opSpecified = false; }
    
    private MapUpdate.FlagOp? _flag_op;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"flag_op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MapUpdate.FlagOp flag_op
    {
      get { return _flag_op?? MapUpdate.FlagOp.ENABLE; }
      set { _flag_op = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool flag_opSpecified
    {
      get { return this._flag_op != null; }
      set { if (value == (this._flag_op== null)) this._flag_op = value ? this.flag_op : (MapUpdate.FlagOp?)null; }
    }
    private bool ShouldSerializeflag_op() { return flag_opSpecified; }
    private void Resetflag_op() { flag_opSpecified = false; }
    
    private MapOp _map_op = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"map_op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapOp map_op
    {
      get { return _map_op; }
      set { _map_op = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"FlagOp")]
    public enum FlagOp
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENABLE", Value=1)]
      ENABLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DISABLE", Value=2)]
      DISABLE = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapOp")]
  public partial class MapOp : global::ProtoBuf.IExtensible
  {
    public MapOp() {}
    
    private readonly global::System.Collections.Generic.List<MapField> _removes = new global::System.Collections.Generic.List<MapField>();
    [global::ProtoBuf.ProtoMember(1, Name=@"removes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapField> removes
    {
      get { return _removes; }
    }
  
    private readonly global::System.Collections.Generic.List<MapUpdate> _updates = new global::System.Collections.Generic.List<MapUpdate>();
    [global::ProtoBuf.ProtoMember(2, Name=@"updates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapUpdate> updates
    {
      get { return _updates; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DtOp")]
  public partial class DtOp : global::ProtoBuf.IExtensible
  {
    public DtOp() {}
    
    private CounterOp _counter_op = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"counter_op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CounterOp counter_op
    {
      get { return _counter_op; }
      set { _counter_op = value; }
    }
    private SetOp _set_op = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"set_op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SetOp set_op
    {
      get { return _set_op; }
      set { _set_op = value; }
    }
    private MapOp _map_op = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"map_op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapOp map_op
    {
      get { return _map_op; }
      set { _map_op = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DtUpdateReq")]
  public partial class DtUpdateReq : global::ProtoBuf.IExtensible
  {
    public DtUpdateReq() {}
    
    private byte[] _bucket;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bucket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] bucket
    {
      get { return _bucket; }
      set { _bucket = value; }
    }
    private byte[] _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] key
    {
      get { return _key?? null; }
      set { _key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool keySpecified
    {
      get { return this._key != null; }
      set { if (value == (this._key== null)) this._key = value ? this.key : (byte[])null; }
    }
    private bool ShouldSerializekey() { return keySpecified; }
    private void Resetkey() { keySpecified = false; }
    
    private byte[] _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _context;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] context
    {
      get { return _context?? null; }
      set { _context = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool contextSpecified
    {
      get { return this._context != null; }
      set { if (value == (this._context== null)) this._context = value ? this.context : (byte[])null; }
    }
    private bool ShouldSerializecontext() { return contextSpecified; }
    private void Resetcontext() { contextSpecified = false; }
    
    private DtOp _op;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DtOp op
    {
      get { return _op; }
      set { _op = value; }
    }
    private uint? _w;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint w
    {
      get { return _w?? default(uint); }
      set { _w = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool wSpecified
    {
      get { return this._w != null; }
      set { if (value == (this._w== null)) this._w = value ? this.w : (uint?)null; }
    }
    private bool ShouldSerializew() { return wSpecified; }
    private void Resetw() { wSpecified = false; }
    
    private uint? _dw;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"dw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dw
    {
      get { return _dw?? default(uint); }
      set { _dw = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dwSpecified
    {
      get { return this._dw != null; }
      set { if (value == (this._dw== null)) this._dw = value ? this.dw : (uint?)null; }
    }
    private bool ShouldSerializedw() { return dwSpecified; }
    private void Resetdw() { dwSpecified = false; }
    
    private uint? _pw;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pw
    {
      get { return _pw?? default(uint); }
      set { _pw = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pwSpecified
    {
      get { return this._pw != null; }
      set { if (value == (this._pw== null)) this._pw = value ? this.pw : (uint?)null; }
    }
    private bool ShouldSerializepw() { return pwSpecified; }
    private void Resetpw() { pwSpecified = false; }
    
    private bool? _return_body;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"return_body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool return_body
    {
      get { return _return_body?? (bool)false; }
      set { _return_body = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool return_bodySpecified
    {
      get { return this._return_body != null; }
      set { if (value == (this._return_body== null)) this._return_body = value ? this.return_body : (bool?)null; }
    }
    private bool ShouldSerializereturn_body() { return return_bodySpecified; }
    private void Resetreturn_body() { return_bodySpecified = false; }
    
    private uint? _timeout;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"timeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timeout
    {
      get { return _timeout?? default(uint); }
      set { _timeout = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timeoutSpecified
    {
      get { return this._timeout != null; }
      set { if (value == (this._timeout== null)) this._timeout = value ? this.timeout : (uint?)null; }
    }
    private bool ShouldSerializetimeout() { return timeoutSpecified; }
    private void Resettimeout() { timeoutSpecified = false; }
    
    private bool? _sloppy_quorum;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"sloppy_quorum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sloppy_quorum
    {
      get { return _sloppy_quorum?? default(bool); }
      set { _sloppy_quorum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sloppy_quorumSpecified
    {
      get { return this._sloppy_quorum != null; }
      set { if (value == (this._sloppy_quorum== null)) this._sloppy_quorum = value ? this.sloppy_quorum : (bool?)null; }
    }
    private bool ShouldSerializesloppy_quorum() { return sloppy_quorumSpecified; }
    private void Resetsloppy_quorum() { sloppy_quorumSpecified = false; }
    
    private uint? _n_val;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"n_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint n_val
    {
      get { return _n_val?? default(uint); }
      set { _n_val = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool n_valSpecified
    {
      get { return this._n_val != null; }
      set { if (value == (this._n_val== null)) this._n_val = value ? this.n_val : (uint?)null; }
    }
    private bool ShouldSerializen_val() { return n_valSpecified; }
    private void Resetn_val() { n_valSpecified = false; }
    
    private bool? _include_context;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"include_context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool include_context
    {
      get { return _include_context?? (bool)true; }
      set { _include_context = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool include_contextSpecified
    {
      get { return this._include_context != null; }
      set { if (value == (this._include_context== null)) this._include_context = value ? this.include_context : (bool?)null; }
    }
    private bool ShouldSerializeinclude_context() { return include_contextSpecified; }
    private void Resetinclude_context() { include_contextSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DtUpdateResp")]
  public partial class DtUpdateResp : global::ProtoBuf.IExtensible
  {
    public DtUpdateResp() {}
    
    private byte[] _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] key
    {
      get { return _key?? null; }
      set { _key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool keySpecified
    {
      get { return this._key != null; }
      set { if (value == (this._key== null)) this._key = value ? this.key : (byte[])null; }
    }
    private bool ShouldSerializekey() { return keySpecified; }
    private void Resetkey() { keySpecified = false; }
    
    private byte[] _context;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] context
    {
      get { return _context?? null; }
      set { _context = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool contextSpecified
    {
      get { return this._context != null; }
      set { if (value == (this._context== null)) this._context = value ? this.context : (byte[])null; }
    }
    private bool ShouldSerializecontext() { return contextSpecified; }
    private void Resetcontext() { contextSpecified = false; }
    
    private long? _counter_value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"counter_value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long counter_value
    {
      get { return _counter_value?? default(long); }
      set { _counter_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool counter_valueSpecified
    {
      get { return this._counter_value != null; }
      set { if (value == (this._counter_value== null)) this._counter_value = value ? this.counter_value : (long?)null; }
    }
    private bool ShouldSerializecounter_value() { return counter_valueSpecified; }
    private void Resetcounter_value() { counter_valueSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<byte[]> _set_value = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(4, Name=@"set_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> set_value
    {
      get { return _set_value; }
    }
  
    private readonly global::System.Collections.Generic.List<MapEntry> _map_value = new global::System.Collections.Generic.List<MapEntry>();
    [global::ProtoBuf.ProtoMember(5, Name=@"map_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEntry> map_value
    {
      get { return _map_value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}