//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riak.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming command requires a callback..
        /// </summary>
        internal static string Riak_Commands_StreamingCommandRequiresCallbackException {
            get {
                return ResourceManager.GetString("Riak_Commands_StreamingCommandRequiresCallbackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; should not have response data but {1} bytes of data present..
        /// </summary>
        internal static string Riak_Core_CommandHasNoResponseTypeButDataPresentException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_CommandHasNoResponseTypeButDataPresentException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; should have response data but {1} bytes of data present..
        /// </summary>
        internal static string Riak_Core_CommandHasResponseTypeButNoDataPresentException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_CommandHasResponseTypeButNoDataPresentException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from the source stream - CanRead is false.
        /// </summary>
        internal static string Riak_Core_ConnectionCanReadIsFalseException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionCanReadIsFalseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send data to server - Can&apos;t write: {0}.
        /// </summary>
        internal static string Riak_Core_ConnectionCantWriteException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionCantWriteException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to read PB message of size {0} bytes but only read {1} bytes..
        /// </summary>
        internal static string Riak_Core_ConnectionDidNotReadFullMessageException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionDidNotReadFullMessageException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|attempt to execute command {1} on connection that is executing another command..
        /// </summary>
        internal static string Riak_Core_ConnectionInFlightException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionInFlightException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|all connections in use / max connections reached..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerAllConnectionsInUseException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerAllConnectionsInUseException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|connection expiration routine is starting..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpirationRoutineStarting_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpirationRoutineStarting_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|connection expiration routine is stopping..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpirationRoutineStopping_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpirationRoutineStopping_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|expired {1} connections..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpiredConnections_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpiredConnections_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|connection manager expiring connections at {1}.
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpiringAt_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpiringAt_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxConnections must be greater than or equal to minConnections..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerMaxMustBeGreaterThanMinException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerMaxMustBeGreaterThanMinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionManagerOptions requires a non-null address..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerRequiresAddressException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerRequiresAddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionManager requires options..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerRequiresOptionsException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerRequiresOptionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|connection returned at shutdown..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerReturnedShutdown_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerReturnedShutdown_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|stop already called. Current state: {1}.
        /// </summary>
        internal static string Riak_Core_ConnectionManagerStopAlreadyCalled_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerStopAlreadyCalled_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|connection count &apos;{1}&apos; does NOT equal queue count &apos;{2}&apos;..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerStopConnectionCountNotEqualQueueCount_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerStopConnectionCountNotEqualQueueCount_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection port must be between 1 and 65535, inclusive..
        /// </summary>
        internal static string Riak_Core_ConnectionPortMustBeInRange {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionPortMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to decode zero byte data response from Riak..
        /// </summary>
        internal static string Riak_Core_ConnectionZeroLengthResponseException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionZeroLengthResponseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message data must not be null when decoding..
        /// </summary>
        internal static string Riak_Core_MessageDataCantBeNull {
            get {
                return ResourceManager.GetString("Riak_Core_MessageDataCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response code is 0 for command {0}.
        /// </summary>
        internal static string Riak_Core_MessageResponseCodeIsZeroException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_MessageResponseCodeIsZeroException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected message code from Riak - expected {0}, actual {1}.
        /// </summary>
        internal static string Riak_Core_MessageUnexpectedResponseCodeException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_MessageUnexpectedResponseCodeException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|running..
        /// </summary>
        internal static string Riak_Core_Running_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_Running_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|shutting down..
        /// </summary>
        internal static string Riak_Core_ShuttingDown_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ShuttingDown_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateManager requires an enum using a byte as the underyling type..
        /// </summary>
        internal static string Riak_Core_StateManagerMustUseByteEnum {
            get {
                return ResourceManager.GetString("Riak_Core_StateManagerMustUseByteEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateManager requires an enum type..
        /// </summary>
        internal static string Riak_Core_StateManagerMustUseEnum {
            get {
                return ResourceManager.GetString("Riak_Core_StateManagerMustUseEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateManager requires at least one state value..
        /// </summary>
        internal static string Riak_Core_StateManagerRequiresAtLeastOneState {
            get {
                return ResourceManager.GetString("Riak_Core_StateManagerRequiresAtLeastOneState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal state! Expected state {0} but got {1}.
        /// </summary>
        internal static string Riak_Core_StateManagerStateCheckExpectedStateButGot_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_StateManagerStateCheckExpectedStateButGot_fmt", resourceCulture);
            }
        }
    }
}
