//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riak.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming command requires a callback..
        /// </summary>
        internal static string Riak_Commands_StreamingCommandRequiresCallbackException {
            get {
                return ResourceManager.GetString("Riak_Commands_StreamingCommandRequiresCallbackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; should not have response data but {1} bytes of data present..
        /// </summary>
        internal static string Riak_Core_CommandHasNoResponseTypeButDataPresentException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_CommandHasNoResponseTypeButDataPresentException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; should have response data but {1} bytes of data present..
        /// </summary>
        internal static string Riak_Core_CommandHasResponseTypeButNoDataPresentException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_CommandHasResponseTypeButNoDataPresentException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from the source stream - CanRead is false.
        /// </summary>
        internal static string Riak_Core_ConnectionCanReadIsFalseException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionCanReadIsFalseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send data to server - Can&apos;t write: {0}:{1}.
        /// </summary>
        internal static string Riak_Core_ConnectionCantWriteException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionCantWriteException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to read PB message of size {0} bytes but only read {1} bytes..
        /// </summary>
        internal static string Riak_Core_ConnectionDidNotReadFullMessageException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionDidNotReadFullMessageException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to execute command {0} on connection that is executing another command..
        /// </summary>
        internal static string Riak_Core_ConnectionInFlightException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionInFlightException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to decode zero byte data response from Riak..
        /// </summary>
        internal static string Riak_Core_ConnectionZeroLengthResponseException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionZeroLengthResponseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message data must not be null when decoding..
        /// </summary>
        internal static string Riak_Core_MessageDataCantBeNull {
            get {
                return ResourceManager.GetString("Riak_Core_MessageDataCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response code is 0 for command {0}.
        /// </summary>
        internal static string Riak_Core_MessageResponseCodeIsZeroException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_MessageResponseCodeIsZeroException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected message code from Riak - expected {0}, actual {1}.
        /// </summary>
        internal static string Riak_Core_MessageUnexpectedResponseCodeException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_MessageUnexpectedResponseCodeException_fmt", resourceCulture);
            }
        }
    }
}
