//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riak.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming command requires a callback..
        /// </summary>
        internal static string Riak_Commands_StreamingCommandRequiresCallbackException {
            get {
                return ResourceManager.GetString("Riak_Commands_StreamingCommandRequiresCallbackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; should not have response data but {1} bytes of data present..
        /// </summary>
        internal static string Riak_Core_CommandHasNoResponseTypeButDataPresentException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_CommandHasNoResponseTypeButDataPresentException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; should have response data but {1} bytes of data present..
        /// </summary>
        internal static string Riak_Core_CommandHasResponseTypeButNoDataPresentException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_CommandHasResponseTypeButNoDataPresentException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from the source stream - CanRead is false.
        /// </summary>
        internal static string Riak_Core_ConnectionCanReadIsFalseException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionCanReadIsFalseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send data to server - Can&apos;t write: {0}.
        /// </summary>
        internal static string Riak_Core_ConnectionCantWriteException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionCantWriteException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected to: {0}.
        /// </summary>
        internal static string Riak_Core_ConnectionConnectedTo_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionConnectedTo_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to read PB message of size {0} bytes but only read {1} bytes..
        /// </summary>
        internal static string Riak_Core_ConnectionDidNotReadFullMessageException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionDidNotReadFullMessageException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|attempt to execute command {1} on connection that is executing another command..
        /// </summary>
        internal static string Riak_Core_ConnectionInFlightException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionInFlightException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|all connections in use / max connections reached..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerAllConnectionsInUseException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerAllConnectionsInUseException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|expiration routine cancelled..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpirationCancelled_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpirationCancelled_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|connection expiration routine is starting..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpirationRoutineStarting_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpirationRoutineStarting_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|connection expiration routine is stopping..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpirationRoutineStopping_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpirationRoutineStopping_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|expiration routine sleeping for {1}.
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpirationSleeping_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpirationSleeping_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|expired {1} connections..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpiredConnections_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpiredConnections_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|expiring connections at {1}.
        /// </summary>
        internal static string Riak_Core_ConnectionManagerExpiringAt_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerExpiringAt_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|expiration thread timeout while waiting for queue lock to iterate on {1} items..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerIteratingConnectionQueueForExpirationTimeout_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerIteratingConnectionQueueForExpirationTimeout_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionManagerOptions requires a non-null address..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerRequiresAddressException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerRequiresAddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionManager requires options..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerRequiresOptionsException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerRequiresOptionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|connection returned at shutdown..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerReturnedShutdown_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerReturnedShutdown_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|connection count &apos;{1}&apos; does NOT equal queue count &apos;{2}&apos;..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerStopConnectionCountNotEqualQueueCount_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerStopConnectionCountNotEqualQueueCount_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|timeout while waiting for expiration thread to complete..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerStopExpirationStopTimeout_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerStopExpirationStopTimeout_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|timeout waiting for queue lock to iterate on {1} items..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerStopIteratingConnectionQueueTimeout_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerStopIteratingConnectionQueueTimeout_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|waiting for expiration task to complete..
        /// </summary>
        internal static string Riak_Core_ConnectionManagerWaitingExpirationTask_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionManagerWaitingExpirationTask_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to decode zero byte data response from Riak..
        /// </summary>
        internal static string Riak_Core_ConnectionZeroLengthResponseException {
            get {
                return ResourceManager.GetString("Riak_Core_ConnectionZeroLengthResponseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|executing command {1}.
        /// </summary>
        internal static string Riak_Core_ExecutingCommand_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ExecutingCommand_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxConnections must be greater than or equal to minConnections..
        /// </summary>
        internal static string Riak_Core_MaxConnectionsMustBeGreaterThanMinConnectionsException {
            get {
                return ResourceManager.GetString("Riak_Core_MaxConnectionsMustBeGreaterThanMinConnectionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message data must not be null when decoding..
        /// </summary>
        internal static string Riak_Core_MessageDataCantBeNull {
            get {
                return ResourceManager.GetString("Riak_Core_MessageDataCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response code is 0 for command {0}.
        /// </summary>
        internal static string Riak_Core_MessageResponseCodeIsZeroException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_MessageResponseCodeIsZeroException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected message code from Riak - expected {0}, actual {1}.
        /// </summary>
        internal static string Riak_Core_MessageUnexpectedResponseCodeException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_MessageUnexpectedResponseCodeException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|health check failed: {1}.
        /// </summary>
        internal static string Riak_Core_Node_HealthcheckFailed_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_Node_HealthcheckFailed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|health check success..
        /// </summary>
        internal static string Riak_Core_Node_HealthcheckSuccess_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_Node_HealthcheckSuccess_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|already health checking or shutting down..
        /// </summary>
        internal static string Riak_Core_NodeAlreadyHealthChecking_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeAlreadyHealthChecking_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|health check routine cancelled..
        /// </summary>
        internal static string Riak_Core_NodeHealthCheckCancelled_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeHealthCheckCancelled_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|health check exception: {1}.
        /// </summary>
        internal static string Riak_Core_NodeHealthCheckException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeHealthCheckException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|health check routine quitting ({1})..
        /// </summary>
        internal static string Riak_Core_NodeHealthCheckQuitting_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeHealthCheckQuitting_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|health check routine sleeping for {1}.
        /// </summary>
        internal static string Riak_Core_NodeHealthCheckSleeping_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeHealthCheckSleeping_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to executed {0} on node {1}.
        /// </summary>
        internal static string Riak_Core_NodeManager_ExecutedCommand_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeManager_ExecutedCommand_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node manager requires a non-null command argument..
        /// </summary>
        internal static string Riak_Core_NodeManagerCommandRequiredException {
            get {
                return ResourceManager.GetString("Riak_Core_NodeManagerCommandRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero nodes for executon of command {0}.
        /// </summary>
        internal static string Riak_Core_NodeManagerZeroLengthNodes_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeManagerZeroLengthNodes_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxConnections must be less than {0}.
        /// </summary>
        internal static string Riak_Core_NodeMaxConnectionsMustBeLessThanException_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeMaxConnectionsMustBeLessThanException_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minConnections must be greater than or equal to 1..
        /// </summary>
        internal static string Riak_Core_NodeMinConnectionsMustBeOneOrGreaterException {
            get {
                return ResourceManager.GetString("Riak_Core_NodeMinConnectionsMustBeOneOrGreaterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node requires address..
        /// </summary>
        internal static string Riak_Core_NodeRequiresAddressException {
            get {
                return ResourceManager.GetString("Riak_Core_NodeRequiresAddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node requires options..
        /// </summary>
        internal static string Riak_Core_NodeRequiresOptionsException {
            get {
                return ResourceManager.GetString("Riak_Core_NodeRequiresOptionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|running health check at {1}.
        /// </summary>
        internal static string Riak_Core_NodeRunningHealthCheckAt_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeRunningHealthCheckAt_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|starting health check routine..
        /// </summary>
        internal static string Riak_Core_NodeStartingHealthCheck_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeStartingHealthCheck_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|timeout while waiting for health check thread to complete..
        /// </summary>
        internal static string Riak_Core_NodeStopHealthCheckStopTimeout_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeStopHealthCheckStopTimeout_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|waiting for health check task to complete..
        /// </summary>
        internal static string Riak_Core_NodeWaitingHealthCheckTask_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_NodeWaitingHealthCheckTask_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be between 1 and 65535, inclusive..
        /// </summary>
        internal static string Riak_Core_PortMustBeInRange {
            get {
                return ResourceManager.GetString("Riak_Core_PortMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|running..
        /// </summary>
        internal static string Riak_Core_Running_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_Running_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate file not found..
        /// </summary>
        internal static string Riak_Core_SecurityManager_ClientCertificateFileNotFound {
            get {
                return ResourceManager.GetString("Riak_Core_SecurityManager_ClientCertificateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|shut down..
        /// </summary>
        internal static string Riak_Core_Shutdown_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_Shutdown_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|shutting down..
        /// </summary>
        internal static string Riak_Core_ShuttingDown_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_ShuttingDown_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|starting..
        /// </summary>
        internal static string Riak_Core_Starting_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_Starting_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateManager is disposed..
        /// </summary>
        internal static string Riak_Core_StateManagerDisposedException {
            get {
                return ResourceManager.GetString("Riak_Core_StateManagerDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateManager requires an enum using a byte as the underyling type..
        /// </summary>
        internal static string Riak_Core_StateManagerMustUseByteEnum {
            get {
                return ResourceManager.GetString("Riak_Core_StateManagerMustUseByteEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateManager requires an enum type..
        /// </summary>
        internal static string Riak_Core_StateManagerMustUseEnum {
            get {
                return ResourceManager.GetString("Riak_Core_StateManagerMustUseEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateManager requires at least one state value..
        /// </summary>
        internal static string Riak_Core_StateManagerRequiresAtLeastOneState {
            get {
                return ResourceManager.GetString("Riak_Core_StateManagerRequiresAtLeastOneState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal state! Expected state {0} but got {1}.
        /// </summary>
        internal static string Riak_Core_StateManagerStateCheckExpectedStateButGot_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_StateManagerStateCheckExpectedStateButGot_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|stop already called. Current state: {1}.
        /// </summary>
        internal static string Riak_Core_StopAlreadyCalled_fmt {
            get {
                return ResourceManager.GetString("Riak_Core_StopAlreadyCalled_fmt", resourceCulture);
            }
        }
    }
}
