#!/usr/bin/env bash

riak_admin=$1
http_port=$2
strong_consistency="${3:-false}"

$riak_admin bucket-type create plain '{"props":{}}'
$riak_admin bucket-type create search_type '{"props":{}}'
$riak_admin bucket-type create maps '{"props":{"datatype":"map"}}'
$riak_admin bucket-type create sets '{"props":{"datatype":"set"}}'
$riak_admin bucket-type create counters '{"props":{"datatype":"counter"}}'
$riak_admin bucket-type create yokozuna '{"props":{}}'
$riak_admin bucket-type create leveldb_type '{"props":{"backend":"leveldb_backend"}}'
$riak_admin bucket-type create memory_type '{"props":{"backend":"mem_backend"}}'

$riak_admin bucket-type activate search_type
$riak_admin bucket-type activate plain
$riak_admin bucket-type activate maps
$riak_admin bucket-type activate sets
$riak_admin bucket-type activate counters
$riak_admin bucket-type activate yokozuna
$riak_admin bucket-type activate leveldb_type
$riak_admin bucket-type activate memory_type

if [[ $strong_consistency == 'true' ]]
then
  $riak_admin bucket-type create consistent '{"props":{"consistent":true}}'
  $riak_admin bucket-type activate consistent
fi

curl -4 -XPUT -H 'Content-type: application/json' localhost:$http_port/buckets/riak_index_tests/props -d '{"props":{"backend":"leveldb_backend"}}'

